### ISSUE TITLE
Redux Issue . Next JS 13

### ISSUE THREAD

**Issue by skelly2022** [Clariity/react-chessboard#100]
"You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build." 

I have boiled it down to it being react chessboard being the reason this error is populating. Has anybody seen this issue before?

**Comment by Clariity** [comment]
I don't understand how this can be an issue with the package, many/most npm packages have minified code?

**Comment by Clariity** [comment]
I've made an update in 4.3.3 in an attempt to address this by ensuring NODE_ENV is set to production when I build the package, try reinstalling the new version to see if that makes a difference

**Comment by Clariity** [comment]
This is because you're running `npm run dev`

If you run `npm run build && npm run start` then there will be no error.

Therefore the error message makes complete sense, it's expected that a development build of redux would be run when in development mode.

**Comment by Clariity** [comment]
Fix applied in 4.3.4
