### ISSUE TITLE
Laggy when render multiple boards

### ISSUE THREAD

**Issue by samuraitruong** [Clariity/react-chessboard#103]
I have UI to listing multiple game on single page and I display the mini board for each game. Initial setup I have 50 items on page and it look still ok and not see any laggy. When I change to 250 items per pages  and page become super laggy , freeze and also can not render the board if i do any activity on them.

**Comment by Manukyanq** [comment]
Hi! If your boards aren't interactive consider to use [react-chessboard-svg](https://www.npmjs.com/package/react-chessboard-svg) library instead.
