### ISSUE TITLE
Is it possible to disable field labels?

### ISSUE THREAD

**Issue by Konstantin9658** [Clariity/react-chessboard#104]
Hello! In general, great project. Can I disable field labels, because I use border-radius and this label have outside a board?

![image](https://github.com/Clariity/react-chessboard/assets/76180339/bec92e7e-dc19-44a6-8330-cf15f54a0432)

**Comment by Manukyanq** [comment]
Hi! `showBoardNotation: boolean` prop is what you are looking for

<img width="866" alt="image" src="https://github.com/Clariity/react-chessboard/assets/42891870/1b61363f-1683-41bb-b006-0bf9e63a691d">


```jsx
    <Chessboard
       ...
      showBoardNotation={false}
```

**Comment by Konstantin9658** [comment]
And maybe you could tell me why when I take the piece it flies somewhere else? On the screen I'm holding a piece to drag it, but it's off the board when I expect it to be near the cursor
![image](https://github.com/Clariity/react-chessboard/assets/76180339/21d71bf2-1e89-4450-86be-76cf6839161e)

**Comment by Konstantin9658** [comment]
Sorry, I'm probably already tired that I didn't even notice. Thanks a lot!
