### ISSUE TITLE
Animation goes wrong way when board is flipped

### ISSUE THREAD

**Issue by alfredbirk** [Clariity/react-chessboard#107]
A bit similar to the other issue I mentioned, but this is more critical I would say. When `boardOrientation="black"`, the animation goes wrong way. It doesn't happen in version 3.0.0, so some later version is to blame.

https://github.com/Clariity/react-chessboard/assets/11172530/ca7e4c32-6af8-46e1-9da8-920904326b36

**Comment by Manukyanq** [comment]
Hi! I founded the problem, Tomorrow I will have free time to open PR with the fixes of the both issues

**Comment by Clariity** [comment]
Fixed in https://github.com/Clariity/react-chessboard/releases/tag/v4.2.1
