### ISSUE TITLE
areArrowsAllowed={false} doesn't work

### ISSUE THREAD

**Issue by Epitomaniac** [Clariity/react-chessboard#111]
Since I updated the package, this option no longer seems to work. Arrows are now allowed whether this property is true or false.

**Comment by Clariity** [comment]
Good find, thank you, are you able to make a PR to fix this? If not then I will fix when I get time (which I have very little of lately)

**Comment by Epitomaniac** [comment]
Unfortunately I have very little free time on my hand too. No pressure though, the library is a blast as it is, cheers!

**Comment by Clariity** [comment]
Fixed in https://github.com/Clariity/react-chessboard/releases/tag/v4.2.3
