### ISSUE TITLE
onPromotionCheck for squareClick

### ISSUE THREAD

**Issue by msabree** [Clariity/react-chessboard#112]
onPromotionCheck does not fire when clicking a square. If you move using square clicks you are forced to manually handle the promotion logic. it'll be better to allow onPromotionCheck to run onSquare click as well and also provide the piece property in that callback.

**Comment by msabree** [comment]
Actually this is not accurate. I see how it works now. Deleting this issue.

**Comment by hassaans** [comment]
@msabree How did you resolve this issue?

**Comment by msabree** [comment]
@hassaans I was mistaken, this is still an issue. I thought that maybe the onPieceDrop event would be fired manually after the dialog showed up but it currently does not. I'll re-open the issue. No dialog appears onSquareClick when promoting.

**Comment by Clariity** [comment]
If you promote in the Click to Move example in storybook you will see that the promotion dialog does popup:

https://react-chessboard.vercel.app/?path=/story/example-chessboard--click-to-move
