### ISSUE TITLE
Animation skips after failed drag move

### ISSUE THREAD

**Issue by MatthewHerrmannDev** [Clariity/react-chessboard#114]
I am trying to implement a chessboard that includes both click-to-move and drag-to-move functionality. I have noticed a strange behavior where the click-to-move animation skips after a failed drag-to-move attempt using the same piece. Does anyone know what might be causing this?

https://github.com/Clariity/react-chessboard/assets/130426098/13d6dac8-7423-44a3-85ef-45c9af5d0647

**Comment by Clariity** [comment]
Fixed in 4.3.2

https://github.com/Clariity/react-chessboard/releases/tag/v4.3.2
