### ISSUE TITLE
Feature Request: Add Circle Annotations to Squares

### ISSUE THREAD

**Issue by hrushidev** [Clariity/react-chessboard#116]
I would like to suggest a new feature for the react-chessboard library: the ability to annotate squares with circles, similar to what we see on Lichess.

Key Points:

What? Users should be able to right-click on a square and mark it with a circle.
Why? This feature is great for highlighting important squares during chess analysis or training.
How? Right-clicking a square adds a circle to it. Right-clicking again removes it.
This feature will make react-chessboard more useful for chess coaching, game analysis, and educational content creation.

Looking forward to your thoughts and feedback on this feature!

![image](https://github.com/Clariity/react-chessboard/assets/122083058/37d44aba-5992-47ba-8aeb-42d92f468865)

**Comment by Clariity** [comment]
If you check the source code for https://react-chessboard.vercel.app/?path=/docs/example-chessboard--click-to-move you will see logic for styling squares on right click

**Comment by Manukyanq** [comment]
Hi, I've made a simple [CodeSandbox](https://codesandbox.io/p/sandbox/vigorous-aj-8my447?file=%2Fsrc%2FApp.js%3A7%2C55&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpazq26100073b6de1gcto90%2522%252C%2522sizes%2522%253A%255B86.19926199261992%252C13.800738007380076%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpazq26100033b6dlyl6djfi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpazq26100043b6dt5h3u9ce%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpazq26100063b6dtzs2pve2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.363018766014115%252C49.636981233985885%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpazq26100033b6dlyl6djfi%2522%253A%257B%2522id%2522%253A%2522clpazq26100033b6dlyl6djfi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb0bvv200033b6dj2uu51x4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A55%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb0bvv200033b6dj2uu51x4%2522%257D%252C%2522clpazq26100063b6dtzs2pve2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpazq26100053b6dhtjx5cxa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpazq26100063b6dtzs2pve2%2522%252C%2522activeTabId%2522%253A%2522clpazq26100053b6dhtjx5cxa%2522%257D%252C%2522clpazq26100043b6dt5h3u9ce%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpazq26100043b6dt5h3u9ce%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)  example, you can check it and style on your own.
Current features of `Chessboard` component should be enough to make it real.

**Comment by hrushidev** [comment]
Hello @Clariity @Manukyanq ,  
Thank you, for the response this was really helpful.
