### ISSUE TITLE
Positioning issue if FEN string changes completely

### ISSUE THREAD

**Issue by Makavto** [Clariity/react-chessboard#117]
Hi! Here is an example of issue:

https://github.com/Clariity/react-chessboard/assets/93901579/9f04b2f2-6d34-4ef5-8078-b37636946ddd

If I change FEN to a couple of moves it's ok, but if I change it to the start of the game it messes things up :(

Is there any way to fix it?

**Comment by Manukyanq** [comment]
Hi @Makavto! Can you please provide code how FEN position's change works, and check which value for start position do you set, when you click on first move. Also please tell me which version of `react-chessboard` do you use?

**Comment by Manukyanq** [comment]
I guess the problem is here in `useEffect`: The `game.load()` method change's Chess objects, but doesn't make your `Chessboard` component rerender 
```
  useEffect(() => {
    if (!!startingFen) {
      game.load(startingFen);
      checkDangerSquares();
      // here will be setGame() call which will be make your component rerender `Chessboard`
    }
  }, [startingFen])
```

**Comment by Makavto** [comment]
I've tried it with `setGame()` like this:
```
useEffect(() => {
    if (!!startingFen) {
      setGame(new Chess(startingFen));
      checkDangerSquares();
    }
  }, [startingFen])
```
and it didn't work either :(

I will try `useMemo` approach

**Comment by Manukyanq** [comment]
Can you please also try to  comment `customSquare={CustomSquare}` line and check, is the issue still appears? Make sure your custom style squares have right css position props

**Comment by Makavto** [comment]
Yes! You are right, the problem was in custom squares! I will edit styles for them.
Thanks a lot for your help!
