### ISSUE TITLE
Premove back to existing premove square causes piece to disappear

### ISSUE THREAD

**Issue by jamestickle** [Clariity/react-chessboard#118]
Please see image. I couldn't see a reference to this in existing issues or in closed issues. 

![disappearedPieceOnPremove](https://github.com/Clariity/react-chessboard/assets/143610265/72780595-d567-4c2e-b866-1593821361dd)

**Comment by Clariity** [comment]
Please provide steps to reproduce on https://react-chessboard.vercel.app/?path=/story/example-chessboard--premoves-enabled

**Comment by jamestickle** [comment]
Make a premove with any piece (not pawn), then make another premove back to original square. The same thing will occur if premoving to any square that has already been premoved to/from.

**Comment by Clariity** [comment]
Thank you, I can see this is an issue, currently extremely busy with other projects so won't get much time to look at this. If you have time please have a look and raise a PR, if not then I will have to address this at some point next year

**Comment by jamestickle** [comment]
Sure. Any clues on where to start looking?

**Comment by Clariity** [comment]
https://github.com/Clariity/react-chessboard/blob/main/src/chessboard/components/Piece.tsx#L86

Somewhere in this logic I think

**Comment by Clariity** [comment]
Fixed in #120, will be in next release
