### ISSUE TITLE
Feature Request: Exposing the `Square` and `PieceSymbol` in the `onSquareClick()` and `onPieceClick()` handlers

### ISSUE THREAD

**Issue by GabrielCTroia** [Clariity/react-chessboard#127]
# What

### OnPieceClick Handler
I'm suggesting adding the Square to the `onPieceClick()` handler, like:

`onPieceClick?: (piece: Piece) => any;` -> `onPieceClick?: (piece: Piece, square: Square) => any;`

### OnSquareClick Handler
I'm suggesting adding the Piece to the `onSquareClick()` handler, like:

`onSquareClick?: (square: Square) => any;` -> `onSquareClick?: (square: Square, piece?: Piece) => any;`

# Why
Sometimes you need know the square the piece was clicked on, or vice-versa, and doing so in the current implementation either requires to do some un-ideal hacks of combining `onSquareClick` & `onPieceClick` together + a timer, or depend on a Board interpreter like Chess.js to grab them.

**Comment by Clariity** [comment]
Currently working on other projects that are taking up all of my time, this seems like a reasonable request that is simple to add, would you mind raising a PR for it?

**Comment by KeeghanM** [comment]
Made a PR for these
https://github.com/Clariity/react-chessboard/pull/130

**Comment by FlynnHillier** [comment]
> Made a PR for these #130

Wow, I literally just made a start on this feature haha. The timing is crazy.

**Comment by KeeghanM** [comment]
> > Made a PR for these #130
> 
> Wow, I literally just made a start on this feature haha. The timing is crazy.

Oh no! Bad timing, well take a look and see if you'd have done it different/better :)

**Comment by FlynnHillier** [comment]
> > > Made a PR for these #130
> > 
> > 
> > Wow, I literally just made a start on this feature haha. The timing is crazy.
> 
> Oh no! Bad timing, well take a look and see if you'd have done it different/better :)

No your implementation looks much the same. You beat me to it! fair game. 

Also on an entirely unrelated and even more coincidental note - I see you are also from Liverpool and also climb at the Climbing hangar 😂 Extremely coincidental interaction haha

**Comment by Clariity** [comment]
Released in https://github.com/Clariity/react-chessboard/releases/tag/v4.5.0

**Comment by GabrielCTroia** [comment]
Thank you @Clariity, @FlynnHillier & @KeeghanM 🙏
