### ISSUE TITLE
Show Dead Pieces

### ISSUE THREAD

**Issue by tempestshad0w** [Clariity/react-chessboard#133]
How can I show dead pieces outside the board during the game?

**Comment by Manukyanq** [comment]
Hi! I guess, this question is not related to `react-chessboard` at all (( Everything outside the board is not the responsibilty of `react-chessboard`. The logic of extracting captured pieces from game state  depends on your code and on the libraries you use. If you use `chess.js` this method might be helpful:  [chess.history()](https://github.com/jhlywa/chess.js/blob/master/README.md#history-options-)

**Comment by Clariity** [comment]
Closing as unrelated / will be able to load spare pieces in #88
