### ISSUE TITLE
pieces dont snap back into place in touch screen

### ISSUE THREAD

**Issue by thornxyz** [Clariity/react-chessboard#134]
When i make a wrong move on my phone, the piece does not snap back into place and just stay there till i drag it back. This issue does not happen on pc though. Can someone help me figure out what's wrong, it might be something to do with the version.

Here is link to the website: https://playstockfish.vercel.app

Here is the link to my source code: https://github.com/thornxyz/chess_website

**Comment by Clariity** [comment]
You're using `"chess.js": "^1.0.0-beta.8",` but using the 0.X.X version syntax.

I've cloned and installed `chess.js@0` and it works as expected on mobile

**Comment by thornxyz** [comment]
Thank you, it worked!
