### ISSUE TITLE
Issue with promotion

### ISSUE THREAD

**Issue by barakdaniel1** [Clariity/react-chessboard#135]
Hello!
I just started using this package.
This is my code so far:

import { Chessboard } from 'react-chessboard';
import {Chess} from 'chess.js';
import { useState } from 'react';
import './App.css'

const App = () => {
  const [chess] = useState(new Chess());
  const [board,setBoard] = useState("start");
  
  const handleMove = (source, target, promotion) =>{
    console.log(promotion);
    try{
        const move = chess.move({from: source, to: target, promotion: promotion});
        setBoard(chess.fen());
    }
    catch(error){
      console.log(error);
      return;
    }
    
  }

  return (
    <div className='board-container'>
      <Chessboard position={board}
                  onPieceDrop={handleMove}
                  boardWidth={560}
                  promotionDialogVariant={'vertical'}
                  promotionToSquare={['a1','a2','a3','a4','a5','a6','a7','a8',
                                      'h1','h2','h3','h4','h5','h6','h7','h8']}/>
    </div>
  )
}

export default App;

If I remove the "promotion" argument from my handleMove function, and just define the promotion to 'q' in the chess.move(), then everything is working.
However, at this current state, no matter which piece I choose to promote to, I get an "Invalid move" error, despite having the correct arguments.

![chessError](https://github.com/Clariity/react-chessboard/assets/132214852/bed09faf-8713-42ef-9624-2f47b03d5ee3)

Thank you in advance for any help 

P.S - I couldn't get my code to display here as code for some reason, so it's quite hard to read, sorry for that.

**Comment by Manukyanq** [comment]
Hi! Promotion field should reprezent  to which piece you want to promote your pawn, which has reached to the final line. In `chess.js` library It can be only one of the listed values ['q', 'r', 'b', 'n']. Try this instead: 

```
**try{
    const move = chess.move({from: source, to: target, promotion:  promotion[1].toLowerCase() ?? "q"});
    setBoard(chess.fen());
}**
```

**Comment by barakdaniel1** [comment]
> Hi! Promotion field should reprezent to which piece you want to promote your pawn, which has reached to the final line. In `chess.js` library It can be only one of the listed values `['q', 'r', 'b', 'n']`. Try this instead:
> 
> ```js
> try{
>     const move = chess.move({from: source, to: target, promotion:  promotion[1].toLowerCase() ?? "q"});
>     setBoard(chess.fen());
> }
> ```

Brilliant, it worked!!
Thank you so much, I can't believe I missed such a detail haha.
