### ISSUE TITLE
Install package failed

### ISSUE THREAD

**Issue by lexuantunght** [Clariity/react-chessboard#14]
Please check this issue, reproduce steps:
1. npx create-react-app@latest my-chess
2. cd my-chess
3. npm i react-chessboard

Error details:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@12.1.2
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^12.1.2" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @testing-library/react@12.1.2
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^12.1.2" from the root project
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     1 more (react-chessboard)
npm ERR!   4 more (react-scripts, the root project, react-chessboard, react-dnd)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-dnd-preview@6.0.2
npm ERR! node_modules/react-dnd-multi-backend/node_modules/react-dnd-preview
npm ERR!   react-dnd-preview@"^6.0.2" from react-dnd-multi-backend@6.0.2
npm ERR!   node_modules/react-dnd-multi-backend
npm ERR!     react-dnd-multi-backend@"^6.0.2" from react-chessboard@1.0.4
npm ERR!     node_modules/react-chessboard
npm ERR!       react-chessboard@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Clariity** [comment]
Attempting internal fix with new release

**Comment by Clariity** [comment]
Hopefully fixed in https://github.com/Clariity/react-chessboard/releases/tag/v1.0.5 

Please try again and confirm
