### ISSUE TITLE
Small artifact on a1 when hovering square (only on Microsoft Edge)

### ISSUE THREAD

**Issue by alexandrelipp** [Clariity/react-chessboard#141]
When hovering a1, a small blue artifact appears. Only present on Microsoft Edge

 This example is taken from the storybook configurable board

https://github.com/Clariity/react-chessboard/assets/57871230/a3ba3b77-2658-48ac-8a57-cbdcd22c09c1

**Comment by Clariity** [comment]
Just tried on Edge and didn't get the issue

was only able to recreate when holding down the mouse button, perhaps something is going on there? or you have a touch screen device?

**Comment by alexandrelipp** [comment]
Oh yes sorry I forgot to precise you have to hold the mouse button down. It is not a screen device

**Comment by Clariity** [comment]
if you hold the mouse button down whilst entering the board then you are just highlighting the text of the board, if you want to remove the text then you can disable the notation with showBoardNotation = false

**Comment by alexandrelipp** [comment]
I still want the see the notation. I was able to fix the problem by wrapping the chessboard in an element with `user-select: none;` . That way I can still see the notation but can't highlight anything in the chess board.
