### ISSUE TITLE
Nextjs Error

### ISSUE THREAD

**Issue by SamarthKadam** [Clariity/react-chessboard#145]
I tried embedded this file in nextjs but its giving me this error Error: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function

**Comment by ahofmeister** [comment]
Can you please post your solution? It might help others.

**Comment by captainsano** [comment]
I was able to solve it by wrapping it as a ClientComponent:

```tsx
"use client"

import { Chessboard as ReactChessboard, ChessboardOptions } from "react-chessboard"

export const Chessboard = ({ options }: { options?: ChessboardOptions }) => {
  return <ReactChessboard options={options} />
}
```
