### ISSUE TITLE
Promotion issue

### ISSUE THREAD

**Issue by quackquavk** [Clariity/react-chessboard#148]
When a piece is promoted how can I know to what piece its promoted to because onDrop only returns from and to so when the player has to promote to sth else

**Comment by DevArches** [comment]
`onPieceDrop?: ((sourceSquare: Square, targetSquare: Square, piece: Piece) => boolean) | undefined`
Not sure what you mean about it only returning from and to. 
I  just check if the piece that is being dragged is the piece that is being returned when dropped. If not, then it's a promotion piece.

**Comment by Clariity** [comment]
```
function onDrop(sourceSquare, targetSquare, piece) {
    const gameCopy = { ...game };
    const move = gameCopy.move({
      from: sourceSquare,
      to: targetSquare,
      **promotion: piece[1].toLowerCase() ?? "q",**
    });
    setGame(gameCopy);

    ...
```

the onDrop function returns a piece that you can use to set promotion, the above is an example with chess.js
