### ISSUE TITLE
I successfully integrated click to move funtionality but it doesn't work with premoves.

### ISSUE THREAD

**Issue by quackquavk** [Clariity/react-chessboard#153]
`
  const onSquareClick = useCallback(
    (square) => {
      if (selectedSquare === null) {
        const piece = game.get(square);
        if (piece && piece.color === game.turn()) {
          setSelectedSquare(square);
          setPotentialSourceSquare(square);
        }
      } else {
        const moves = getPossibleMoves(selectedSquare);
        const move = { ...moves.find((m) => m.to === square) };
        if (move) {
          if (move.promotion) {
            setSelectedSquare(square);
            setPromotionDialogue(true);
            setPromotionToSquare(move.to);
          } else {
            const newGame = new Chess(game.fen());
            const result = newGame.move(move);
            if (result) {
              onDrop(move.from, move.to);
            }
          }
        }
        setSelectedSquare(null);
      }
    },
    [game, selectedSquare, getPossibleMoves]
  );`

this the function im using. help me please

**Comment by Clariity** [comment]
Please format the code block to be readable using ``` around your code instead of `

**Comment by Clariity** [comment]
Click to move with premoves is not currently supported within the component, but you should be able to implement your own logic outside of the component by storing your own premove queue, updating square colors and running updates when `getPositionObject` is called on position change

**Comment by quackquavk** [comment]
Thanks, I'll do just that!
