### ISSUE TITLE
SparePiece does not get dragged.

### ISSUE THREAD

**Issue by sbeben** [Clariity/react-chessboard#156]
Hello there, thanks for your amazing library!

I am building a chess app, where in the beginning you have to place pieces by yourself. Seems like SparePiece component is a perfect solution for me. But, when I use it like this:
```
 <DnDProvider backend={HTML5Backend}>
        <Board
          boardWidth={400}
        />
        <SparePiece width={40} piece="bB" dndId={"123123"} />
      </DnDProvider>
```
i can grab the piece, but it's not following my cursor. However, if i continue to drag and drag over the board - the squares start to glow yellow and when I drop it - it takes it's place on the board.
So, everything is perfect, except the piece is not following the cursor while being dragged.

Don't you think this behaviour should be implemented by default? Can you even accomplish that? Is there any workaround on your mind for that?
With regards.

**Comment by Clariity** [comment]
Please follow the example shown in the Storybook

https://react-chessboard.vercel.app/?path=/story/chessboard--manual-board-editor
