### ISSUE TITLE
"Invariant Violation: Expected drag drop context" error in Next.js 14.2.9 with react-chessboard 4.7.1

### ISSUE THREAD

**Issue by nsalewski** [Clariity/react-chessboard#158]
I get an "Invariant Violation: Expected drag drop context" error when using react-chessboard in a Next.js 14.2.9 project. The error stays even after updating to the latest version of react-chessboard.

Environment:
- Next.js: 14.2.9
- React: 18.x
- react-chessboard: 4.7.1 (updated from 4.6.0, same error)
- react-dnd: 16.0.1
- react-dnd-html5-backend: 16.0.1
- react-dnd-touch-backend: 16.0.1

Error message:
`1 of 1 errorNext.js (14.2.9)
Unhandled Runtime Error
Invariant Violation: Expected drag drop context
Call Stack
invariant
node_modules/react-chessboard/dist/index.esm.js (1257:1)
useDragDropManager
node_modules/react-chessboard/dist/index.esm.js (3330:1)
useDragLayer
node_modules/react-chessboard/dist/index.esm.js (3483:1)
CustomDragLayer
node_modules/react-chessboard/dist/index.esm.js (5646:1)
React`

This setup worked correctly in a previous project with similar dependencies. Explicitly installing the same versions of react-dnd and related packages as used by react-chessboard did not resolve the issue. 

I've tried:
- Clearing node_modules and reinstalling dependencies
- Explicitly installing react-dnd and related packages
- Going back to react-chessboard 4.6.0

Any help would be appreciated!

**Comment by shinebarbhuiya** [comment]
Same error here

**Comment by Clariity** [comment]
Please provide a minimal reproduction

I've just run:

```
npx create-next-app@latest
npm i react-chessboard   
```

then set `app/page.tsx` to:

```
"use client";
import { Chessboard } from "react-chessboard";

export default function Home() {
  return (
    <div style={{ width: "500px" }}>
      <Chessboard position="start" />
    </div>
  );
}
```

ran with

```
npm run dev
```

and all is working as expected

node version: `v20.11.0`
browser: chrome

**Comment by DevArches** [comment]
This is incredibly hard to read. Could you condense it to the most important parts? Are you giving it a custom dnd-backend or just using the default?

**Comment by nsalewski** [comment]
> I've tried:
> 
> * Clearing node_modules and reinstalling dependencies
> * Explicitly installing react-dnd and related packages
> * Going back to react-chessboard 4.6.0

What makes it hard to read? I got rid off the code example which is maybe too long and wrongly formatted?

I tried both but lately sticking to the default one.

**Comment by nsalewski** [comment]
> This is incredibly hard to read. Could you condense it to the most important parts? Are you giving it a custom dnd-backend or just using the default?

What makes it hard to read? I got rid off the code example which is maybe too long and wrongly formatted?

I tried both but lately sticking to the default one.

**Comment by nsalewski** [comment]
> Please provide a minimal reproduction
> 
> I've just run:
> 
> ```
> npx create-next-app@latest
> npm i react-chessboard   
> ```
> 
> then set `app/page.tsx` to:
> 
> ```
> "use client";
> import { Chessboard } from "react-chessboard";
> 
> export default function Home() {
>   return (
>     <div style={{ width: "500px" }}>
>       <Chessboard position="start" />
>     </div>
>   );
> }
> ```
> 
> ran with
> 
> ```
> npm run dev
> ```
> 
> and all is working as expected
> 
> node version: `v20.11.0` browser: chrome

Okay, I found the problem. I used

`<Chessboard position="start" boardWidth={500} />`

 before instead of

`<div style={{ width: "500px" }}>
      <Chessboard position="start" />
    </div>`.
    
 I guess the dnd context isn't handling the boardWidth prop correctly. Now it works when I keep the default Chessboard size and it then adjusts to the div size.
 
Thanks for your help!
