### ISSUE TITLE
Super irritating Erroe - Invariant Violation: Expected drag drop context

### ISSUE THREAD

**Issue by shinebarbhuiya** [Clariity/react-chessboard#159]
![image](https://github.com/user-attachments/assets/3ca411f6-0e5b-4834-ac10-5e32a6d7b846)

Please fix this issue for Nextjs

**Comment by LunarEclipseCode** [comment]
Can you try switching from version 4.7.1 to 4.7.0 ? After making this change, I am not seeing this error anymore in my project.

**Comment by Clariity** [comment]
Closing as duplicate of https://github.com/Clariity/react-chessboard/issues/158
