### ISSUE TITLE
Castling Right issue in Manual Board Editor

### ISSUE THREAD

**Issue by Pratikdubey7735** [Clariity/react-chessboard#169]
Hi Sir, I hope this message finds you well. I am reaching out to seek assistance regarding an issue I've encountered with the FEN generator in application that utilizes the Manual Board Editor feature.

Currently, when generating FEN strings for chess positions, I have noticed that the castling rights are not being correctly added. This issue is impacting the accurate representation of board states, particularly in scenarios where castling is a viable move. As you know, the correct representation of castling rights is crucial for the integrity of chess gameplay and analysis.

**Comment by Clariity** [comment]
Please provide a minimum reproducible example

**Comment by Pratikdubey7735** [comment]
Actually Sir I was using the Manual setup board feature where we can setup
board manually and generate a FEN and I was sending that FEN to another
component where I was trying to play that FEN so when that FEN is loaded on
Chessboard then I am unable to do castling because in FEN castling rights
is not there. Can you suggest me some way to resolve it.

**Comment by Pratikdubey7735** [comment]
Sir no any update after that. Can you please help me for that?

**Comment by Pratikdubey7735** [comment]
Ok, thanks for the clarification.

**Comment by Pratikdubey7735** [comment]
No worries, thanks for the heads up!
