### ISSUE TITLE
How to remove border when dragging piece vver the board?

### ISSUE THREAD

**Issue by vmonastyrov** [Clariity/react-chessboard#177]
Hello,

I hope you're doing well. I am trying to figure out how to disable the 5-pixel border that appears when dragging a piece over the board. I am encountering the same issue described in [this issue](https://github.com/Clariity/react-chessboard/issues/80), but I need to ensure that the border is completely removed, not just the flashing. I have tried overriding the styles for the square in the onDragOverSquare function, but it doesn't seem to work. My background appears, but the border still shows up as well.

Thanks in advance for your help!

**Comment by Epitomaniac** [comment]
customDropSquareStyle={null}
