### ISSUE TITLE
Styled Board + snapToCursor breaks

### ISSUE THREAD

**Issue by robbertkl** [Clariity/react-chessboard#20]
Just checked https://react-chessboard.com and only on the Styled Board, while dragging, I see this:

<img width="553" alt="Screen Shot 2022-02-20 at 03 25 27" src="https://user-images.githubusercontent.com/5704510/154825979-4866bdc9-a885-4420-9f1a-1c3967d4e097.png">

(on Safari 15.3 @ macOS Monterey)

Seems to be related to the new snapToCursor, although weirdly enough in my own setup (where I also use custom pieces with images) I don't have this issue. There I'm using background-image on DIVs, so my guess is this is related to dragging IMGs. They have a default drag preview which was probably always there for IMGs, but wasn't really noticeable before snapToCursor because they lined up perfectly.

If this is indeed the case, I'm not sure it can be fixed in the lib, but there are a few workarounds for people to use (and can be applied to the Styled Board example):
- switching to DIVs with a background-image
- turning off snapToCursor
- switching to a different react-dnd backend (see also #19), because this probably only happens on HTML5Backend

**Comment by Clariity** [comment]
Good catch, are you able to submit a PR to set the styled board example to use DIV's with a background image please if you have the time, if not I will have a go later on this week

**Comment by robbertkl** [comment]
Sure, see #21
