### ISSUE TITLE
Cancelling a premove causes you to not be able to make another premove

### ISSUE THREAD

**Issue by DevinParentice** [Clariity/react-chessboard#22]
If you make a premove, then right click to cancel it, if you try to make another premove before your opponent makes their move it does not register, and snaps the piece back to the original square. You can also see this behavior at https://react-chessboard.com/ with the Premove vs. Random example.

**Comment by Clariity** [comment]
Great find, fixed in [9185030287d7031a815c0a67b365f06c75c2bd90 ](https://github.com/Clariity/react-chessboard/commit/9185030287d7031a815c0a67b365f06c75c2bd90)
