### ISSUE TITLE
Use return value of onPieceDrop to actually move the piece, or change the docs

### ISSUE THREAD

**Issue by jonathanhertz-cic** [Clariity/react-chessboard#25]
Currently, the implementation functions so that devs have to keep track of the state of the game manually when using the onPieceDrop. The docs say that you should return whether the move was valid or not, leading me to believe that this is a function that I can use to control whether the move was valid, and the board will then move it based on whether that was true or false, instead of me having to keep track of that state. I had to go look through the source code and find a comment in the 10k line script that says that this state has to manually be stored and applied to the board.

I think that just having it to be able to control whether the move is valid or not would be the best solution, as that means that it is possible to use this function without having to keep the state manually. At the very least, the docs should clearly state this, and perhaps even comment about it in the example.

**Comment by jonathanhertz-cic** [comment]
Very well, but I think the docs on the onPieceDrop should be updated to mention that the return value does not control whether or not the piece was placed.

**Comment by Clariity** [comment]
Done, thanks for the suggestion.
