### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by kuantuna** [Clariity/react-chessboard#3]
Firstly, thanks for the library. Unfortunately I got the following error, with the "Bare Minimum" and "Basic Example" examples. Probably there is a bug. 

![bug](https://user-images.githubusercontent.com/66808459/133894577-7278bc0b-87a7-4aa9-bbf0-f2dadfd80a1c.png)

**Comment by Clariity** [comment]
Hello, thanks for reporting the issue, are you able to share the steps used to replicate this issue please?

Also, what version of Node are you using? As optional chaining is used which requires node v14.

I'm currently on holiday, when I'm back next week I will look into seeing if I can get the optional chaining transpiled so it works with lower node versions if that's even possible

**Comment by Clariity** [comment]
Another possible cause is that your linter doesn't like it, how up to date is your linter/eslint? As I have created a project separately with Create React App and another one with Create Next App and have been able to load the module fine.

**Comment by kuantuna** [comment]
Thanks a lot for your time. Of course, currently I am using node v14.15.1. And my steps were

1.  `npx create-react-app <my-project-name>`
2.  `cd <my-project-name>`
3.  `npm i react-chessboard`
4.  Then, I have opened the project in VSCode (with `code .`) and navigated into the src/App.js file
5.  Later, I have copied all of the code portion from there (https://github.com/Clariity/react-chessboard#bare-minimum)
6.  Deleted everything in src/App.js and pasted the code that I have copied
7.  Finally, saved the code and run `npm start`

And I got the error. About the linter, I am using the _dbaeumer.vscode-eslint_ (v2.1.25) extension in VSCode (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint). It doesn't warn me about anything before running `npm start` though.

**Comment by Clariity** [comment]
![image](https://user-images.githubusercontent.com/30983280/133944065-5b2a505b-2ec7-41f0-9999-d01ad3b528f2.png)

I have just set up a new project using the same version of node and I checked the version of ESLINT that I have installed and everything is working as expected. Are you able to try the command `eslint -v` and see if that version matches?

**Comment by kuantuna** [comment]
I tried `eslint -v` but didn't work for me. So I installed it globally and tried again and now the version is the same with yours. Tried to compile project again but still got an error, that's why I have upgraded node and npx versions to the latest ones. Tried it again but still had the error. Finally I have tried to compile the project in ubuntu (from wsl), and it worked. Still don't know why but I can't seem to make it work in windows, but at least it's working in the ubuntu :)

**Comment by Clariity** [comment]
My system is Windows and it works so I don't think it's OS based

Now you've installed eslint globally, are you able to try and make the project again from scratch in a new window/new terminal, ensuring the latest versions are set. Might have just needed a reset once installed.

**Comment by kuantuna** [comment]
I have tried it again now, but it still doesn't work.  While installing react-chessboard the npm log was saying that it had some conflicting dependencies, could it be causing the problem?

```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dnd-multi-backend@6.0.2
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"17.0.2" from react-dom@17.0.2
npm WARN   node_modules/react-dom
npm WARN     peer react-dom@"*" from @testing-library/react@11.2.7     
npm WARN     node_modules/@testing-library/react
npm WARN     2 more (the root project, react-chessboard)
npm WARN   5 more (react-scripts, @testing-library/react, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13" from react-dnd-multi-backend@6.0.2        
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from react-chessboard@0.0.5
npm WARN   node_modules/react-chessboard
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.13" from react-dnd-multi-backend@6.0.2
npm WARN   node_modules/react-dnd-multi-backend
npm WARN     react-dnd-multi-backend@"^6.0.2" from react-chessboard@0.0.5
npm WARN     node_modules/react-chessboard
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dnd-multi-backend@6.0.2
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"*" from @testing-library/react@11.2.7
npm WARN   node_modules/@testing-library/react
npm WARN     @testing-library/react@"^11.1.0" from the root project
npm WARN   2 more (the root project, react-chessboard)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13" from react-dnd-multi-backend@6.0.2
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from react-chessboard@0.0.5
npm WARN   node_modules/react-chessboard
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.13" from react-dnd-multi-backend@6.0.2
npm WARN   node_modules/react-dnd-multi-backend
npm WARN     react-dnd-multi-backend@"^6.0.2" from react-chessboard@0.0.5
npm WARN     node_modules/react-chessboard
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 25 packages, changed 87 packages, and audited 1728 packages in 1m

131 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (17 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by Clariity** [comment]
It looks like you aren't creating from scratch as a lockfile is identified, I am unable to replicate this issue. It seems very likely this is down to your local project configuration.

I just created a new folder, ran `npx create-react-app test` `cd test` `npm i react-chessboard` and it worked perfectly as expected.
