### ISSUE TITLE
Some drawbacks

### ISSUE THREAD

**Issue by c0ncentus** [Clariity/react-chessboard#34]
Hi,

According to the playground https://react-chessboard.com/

1. the exchange King-rook (O-O) dont work and i suppose (O-O-O) dont work [king's side and queen's side]
2. no dots of mouvement possibilities
3. no red color or something when ennemy king have danger

as a chess player the basics are not here (1)

**Comment by Clariity** [comment]
1. I can confirm that castling does work
2. Dots of movement possibilities are shown on the Styled Squares example
3. Red colour for enemy king in danger is very much doable with react-chessboard

Please remember that this package is just the board, all logic is handled externally, please thoroughly read the documentation in the README
