### ISSUE TITLE
Responsive boardWidth not working

### ISSUE THREAD

**Issue by aniq-makrani** [Clariity/react-chessboard#40]
Hello,

I am new to react and chessboard js.
i am using your basic 'click to move' code , my issue is with board width, its not responsive.  can you pls help me with this.

**Comment by Clariity** [comment]
check out the example here:

https://github.com/Clariity/react-chessboard/blob/main/example/src/index.js

**Comment by aniq-makrani** [comment]
The issue is solved, thank you very much.
