### ISSUE TITLE
When the container div of the board has a transform: translate it does this

### ISSUE THREAD

**Issue by zekicaneksi** [Clariity/react-chessboard#41]
My mouse is actually at where the the blue marking is.
And when i remove the transform: translate(-50%,-50%) property of the container div, the problem resolves.

Any ideas? Or i could prove more info if needed.

edit: under the blue marking, there is nothing. i first wanted to mark with black pen but i thought it would be hard to notice. then i marked with the blue pen at the same spot. sorry for confusion.

![image](https://user-images.githubusercontent.com/59491631/179580604-d8786833-d869-4fc7-a9f4-497178fb459b.png)

**Comment by Clariity** [comment]
My guess is that the pieces are hovering over where the board would be if there was no transform on the container div?

My recommendation is to not translate the board if possible, unless there's a necessary reason to do so, and instead just position it correctly without the need for translations

**Comment by zekicaneksi** [comment]
> My guess is that the pieces are hovering over where the board would be if there was no transform on the container div?
> 
> My recommendation is to not translate the board if possible, unless there's a necessary reason to do so, and instead just position it correctly without the need for translations

You guessed right.

What i'm doing is, this:
There are 3 columns in that grey area in the picture.
The left and right  columns' borders are seeable. What's between is the middle column.

What i want to do is, put the chessboard right in the middle of that column. To do this;

i'm getting the clientWidth and clientHeight of this column and see which one is smaller. And then setting the board's width to whichever is smaller.

But i'm stuck at the centering part. Do you think i can do it any other way?

**Comment by Clariity** [comment]
do what you're doing, but make the middle column have 

```
.middleColumn {
    display: flex;
    justify-content: center;
}
```

**Comment by Clariity** [comment]
With how the drag layer is written, the board is not compatible with a translated board, but I think a translated board should be a very rare use case and I struggle to think of a use case where it's required. Feel free to close the issue, and good luck with your project

**Comment by zekicaneksi** [comment]
Alright man. Thanks a lot. <3
