### ISSUE TITLE
I couldn't build the example in my local

### ISSUE THREAD

**Issue by zekicaneksi** [Clariity/react-chessboard#42]
> Test your changes using the example folder `npm run build` `cd example`  `npm start`

Since there are package.json files in only the `example` and `package` folders. And there is the `cd example` command in the explanation, i assume that we run `npm run build` in the package folder. And `npm start` in the example folder.

Before running commands, i of course did `npm install`.

After i do `npm start` all i see is this;

![image](https://user-images.githubusercontent.com/59491631/180294574-da95671f-f9a4-4ff5-9839-80b528e41c7e.png)

Sooo, i tried to change to render to createRoot but other errors just stayed as they are.

So i just wanted to ask what i was doing wrong.

Thanks

**Comment by Clariity** [comment]
My guess is that you have multiple versions of React installed somewhere, run this command and see what is returned

![image](https://user-images.githubusercontent.com/30983280/180327008-26896424-d0e3-4777-8f2b-4cdad92ddfdc.png)

**Comment by Clariity** [comment]
I just did a clean clone

`cd react-chessboard/package && npm i && cd ../example && npm i && npm run rebuild`

**Comment by zekicaneksi** [comment]
I followed my way from the beginning and then your way, in both situations the result and `npm ls react` was the same.
as you suspected, in the example folder i have react 18, and 16 in the package folder. But i do the same things as you. I don't understand what's the case. Pardon my noobiness xd

 example folder;
![image](https://user-images.githubusercontent.com/59491631/180378638-a03b68e0-fddc-49c5-a7e5-35ded7e2c85b.png)

package folder;
![image](https://user-images.githubusercontent.com/59491631/180378780-f77aa831-09a6-4aff-81c9-4e519a425005.png)

I checked out the package.json files, and example folder has   `"react": "^18.2.0"` in the dependency section whereas the package folder  has `"react": ">=16.14.0"` in the PeerDependency section.

My pc for some reason is installing react 16.14.0 even though there is the >= in the PeerDependecy part. and example installs 18.2.0. I mean it's not doing anything wrong after all xD

So, i did `npm update`  in the package folder to match the versions and i checked them afterwards with `npm ls react` command. And error was still the same.

So i did the other way, and tried to match the versions at 16.14.0 by changing the package.json files, and then checked them afterwards by `npm ls react`. And the result was the same BUT i didn't get the createRoot error in the console. I just got the other errors. Here's one;

![image](https://user-images.githubusercontent.com/59491631/180384805-0738b931-96b4-4a96-9e53-5770db247239.png)

So, what do i do here? Am i doing something wrong?

Thanks <3

**Comment by Clariity** [comment]
I think it's something to do with `npm link`

see https://stackoverflow.com/a/69457966/19574735

**Comment by zekicaneksi** [comment]
I did `npm link` in package folder, and then `npm link react-chessboard`  in the example folder.

Then did `npm install` in both.

And finally `npm run build` in the package folder and `npm start` in the example folder.

Result was the same, same errors.

Here are the `npm ls react` s;

-- example folder
![image](https://user-images.githubusercontent.com/59491631/180594336-3b089e6b-fddf-4228-aebb-75484a2efc8e.png)

-- package folder
![image](https://user-images.githubusercontent.com/59491631/180594347-827c4741-95ef-463e-8989-358f0c7f9751.png)

So, everything was the same.

I'm `linking` this issue to my noobiness and will not take your time anymore xD So, closing the issue.

There was just a little bug in the Click To Move example. When you click a piece, then click an empty square and then click to a valid square.  It just does nothing even though it shows the option squares. I fixed it in my own project and wanted to fix this one as well but not a big deal anyway. 

Thanks man <3

**Comment by Clariity** [comment]
Have you tried starting again completely from scratch?

```
git clone git@github.com:Clariity/react-chessboard.git
cd .\react-chessboard\example
npm i
npm start
```


I just did this from my desktop and it worked as expected

**Comment by zekicaneksi** [comment]
I was trying every method from scratch just to be sure already xd

Now, i did only `npm i` and `npm start` and it worked.  And since i was going to fix the issue in the example. i'm set.

But i'm still curious about what was going on when i was building the package. I don't get it.

**Comment by Clariity** [comment]
i'll be honest I'm not too sure myself, it looks to simply be something to do with having multiple versions of react somewhere, but I'm glad it worked finally, and I look forward to your example fix, I'll close this issue now

**Comment by anshullaikar** [comment]
@Clariity Facing the same issue, the following solution you have shared does work:

```
git clone git@github.com:Clariity/react-chessboard.git
cd .\react-chessboard\example
npm i
npm start
```

But if we I want edit the package and rebuild it for testing-
```
cd ..\package
npm i
npm run build
```

Then the example code stops working with the following error: 
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

I have tried the `npm link` solution as well but that is not working for me, please let me know if I am doing anything incorrectly

**Comment by Clariity** [comment]
I just cloned the project onto my desktop and ran the following

```
git clone git@github.com:Clariity/react-chessboard.git
cd .\react-chessboard\example
npm i
npm start
```
Worked fine, stopped the server and then ran:
```
cd ../package
npm i
cd ../example
npm run rebuild
```

Worked as expected. You may have some global version of React installed somewhere?

```
node -v
// v14.15.1

npm -v
// 6.14.8
```
