### ISSUE TITLE
move function doesn't work second time 

### ISSUE THREAD

**Issue by aniq-makrani** [Clariity/react-chessboard#50]
i have a for loop from where i am trying to get fen() with the help of move()

for (var i = 0; i < tempLiveGameMoves.length; i++) {
  let game_movement = game.move(tempLiveGameMoves[i].move, {sloppy:true});
  let gameHistory = game.history({ verbose: true }); 
  tempGameFen.push(game.fen()); 
}

the move() works fine on 1st render but when i update my state it doesn't work, it shows 'null' value. 
can you pls help me understand what am I doing wrong ?

**Comment by Clariity** [comment]
This is a question more related to the Chess.js package and relevant React Hooks knowledge

However I do have some code from ChessOpenings.co.uk that does this so I'll paste it here and close the issue as not relevant to react-chessboard

```
const game = new Chess();
for (let i = 0; i < 4; i++) {
    game.move({ from, to });
}
return game.fen();
```
