### ISSUE TITLE
Chess board not responsive & has a fixed width/height

### ISSUE THREAD

**Issue by christopherkade** [Clariity/react-chessboard#51]
Hey, thanks for all the work you've done here, I'm having fun implementing https://dailychess.club and want it to work on mobile.

Seems like the board has a fixed width and height of `560px` and setting it to anything else doesn't seem to allow it to take 100% of the width of the viewport. I'm not finding any option to allow it to be responsive. 

What's your opinion on the matter? Are you able to make it responsive for mobile phones on your end?

Thanks !

**Comment by Clariity** [comment]
https://github.com/Clariity/react-chessboard/blob/6e4857359c648911647bdd10fa0bdb64c2955d63/example/src/index.js#L16

Please read the docs and the examples for how to set the chessboard size and make it responsive

**Comment by christopherkade** [comment]
That's on me for not seeing this option in the docs. But given most people will have to implement responsiveness, do you think it's worth it to add a bullet point in the "NOTES" or maybe an example in the docs? 
Thanks again

**Comment by Clariity** [comment]
I'm currently working on version 2 which will come with some upgrades such as the board being responsive out the box, written entirely in typescript and adding storybook. This should help to clear up any confusion as I know the current implementation isn't ideal

**Comment by Clariity** [comment]
v2 is now released: https://github.com/Clariity/react-chessboard/releases/tag/v2.0.7

Docs at https://react-chessboard.com
