### ISSUE TITLE
Add `data-piece` attribute to pieces html tags

### ISSUE THREAD

**Issue by snelsi** [Clariity/react-chessboard#53]
This library marks square html tags with `data-square` and `data-square-color`.

But it looks like the pieces don't have any distinguishable className or data-attribute attached to them.
It would be very helpfull to attach `data-piece`  attribute to tags, so they can be selected via CSS

**Comment by Clariity** [comment]
good idea, can you raise a PR to add this?

maybe the field can include the piece and the square it's currently on in order to differentiate between the same piece types?

**Comment by snelsi** [comment]
@Clariity 
Sure, here you go https://github.com/Clariity/react-chessboard/pull/54
