### ISSUE TITLE
Errors When Using Basic Example

### ISSUE THREAD

**Issue by AllardQuek** [Clariity/react-chessboard#55]
### Error 1: Import Error
This is the error I received when using the [basic example](https://github.com/Clariity/react-chessboard#basic-example):

```
Failed to compile.

Attempted import error: 'chess.js' does not contain a default export (imported as 'Chess').
ERROR in ./src/App.js 11:39-44
export 'default' (imported as 'Chess') was not found in 'chess.js' (possible exports: BISHOP, BLACK, Chess, DEFAULT_POSITION, KING, KNIGHT, PAWN, QUEEN, ROOK, SQUARES, WHITE, __esModule, validateFen)

webpack compiled with 1 error
```

#### Attempted Solution
I changed line 2 from
```import Chess from "chess.js";``` to
```import { Chess } from "chess.js";``` 
which now displays the chess board.

### Error 2: Uncaught TypeError
However, upon making a move by dragging and dropping a piece, I get the following error message:
```
Uncaught TypeError: gameCopy.move is not a function
    at makeAMove (App.js:10:1)
    at onDrop (App.js:24:1)
    at handleSetPosition (index.esm.js:4905:1)
    at Object.drop (index.esm.js:5180:1)
    at DropTargetImpl.drop (index.esm.js:2775:1)
    at determineDropResult (index.esm.js:687:1)
    at index.esm.js:670:1
    at Array.forEach (<anonymous>)
    at DragDropManagerImpl.drop (index.esm.js:669:1)
    at Object.drop (index.esm.js:823:1)
```

My suspicion is that the spread operator is not working as intended for some reason. Could this be confirmed and is there any solution for this issue? Thank you!

**Comment by Clariity** [comment]
I'm assuming you're using Chess.js version 1.0.0-alpha?

**Comment by Clariity** [comment]
if so, then see #48 

https://github.com/Clariity/react-chessboard/issues/48#issuecomment-1360410905

**Comment by AllardQuek** [comment]
Yes, I was using Chess.js version 1.0.0-alpha. Switching to Chess.js 0.12.0 worked for me. Thank you!
