### ISSUE TITLE
Customise board size

### ISSUE THREAD

**Issue by oriyash** [Clariity/react-chessboard#56]
I am using this library for a school project and I need to be able to customise the board size as in make 6×6, 9×9...  how do I go about this ?

**Comment by Clariity** [comment]
This package does not have the functionality for this I'm afraid, but I'll consider adding it in the future

Perhaps for your school project you can fork this repo and amend the code accordingly

**Comment by oriyash** [comment]
I have forked and I cant get the storybook to serve can you provide some guidance on the steps to follow please

**Comment by Clariity** [comment]
My guess is that you're maybe not on the correct node version as storybook doesn't play well with node 18+, I'm on v16.19.0 and it works fine.

I'm closing this issue as it is no longer related to the package.
