### ISSUE TITLE
Is it possible to make 9*9 chess board?

### ISSUE THREAD

**Issue by Koodooo** [Clariity/react-chessboard#6]
![image](https://user-images.githubusercontent.com/40170313/146175953-50eef3ba-6d82-4c02-bfe8-19e24e3fa84f.png)

**Comment by Clariity** [comment]
I think it may be possible, but just checking if you are aware that this is simply a board and it doesn't handle any logic. Do you have access to an engine that can handle the chess logic for such a board?

**Comment by Clariity** [comment]
Closing as stale
