### ISSUE TITLE
Example code not working 

### ISSUE THREAD

**Issue by im-ghost** [Clariity/react-chessboard#63]
I'm unable to drop a piece with the exact example code

**Comment by Clariity** [comment]
https://github.com/Clariity/react-chessboard/issues/48 

I'm guessing you're not using chess.js v0.x.x?

**Comment by Clariity** [comment]
updated to show in readme

https://github.com/Clariity/react-chessboard/blob/main/README.md#important-examples-use-the-current-stable-release-of-chessjs-as-of-writing-this-chessjs-v100-is-still-in-beta-these-examples-use-chessjs-0120
