### ISSUE TITLE
Type of prop `customSquare` is missing

### ISSUE THREAD

**Issue by leedavidcs** [Clariity/react-chessboard#64]
When installing `react-chessboard@latest`, the prop `customSquare` is missing on the exported `Chessboard` component.

When looking at `react-chessboard` within `node_modules`:

```ts
export declare const Chessboard: import("react").ForwardRefExoticComponent<Pick<ChessboardProps, "animationDuration" | "areArrowsAllowed" | "arePiecesDraggable" | "arePremovesAllowed" | "boardOrientation" | "boardWidth" | "clearPremovesOnRightClick" | "customArrows" | "customArrowColor" | "customBoardStyle" | "customDarkSquareStyle" | "customDndBackend" | "customDndBackendOptions" | "customDropSquareStyle" | "customLightSquareStyle" | "customPieces" | "customPremoveDarkSquareStyle" | "customPremoveLightSquareStyle" | "customSquareStyles" | "dropOffBoardAction" | "id" | "isDraggablePiece" | "getPositionObject" | "onArrowsChange" | "onDragOverSquare" | "onMouseOutSquare" | "onMouseOverSquare" | "onPieceClick" | "onPieceDragBegin" | "onPieceDragEnd" | "onPieceDrop" | "onSquareClick" | "onSquareRightClick" | "position" | "showBoardNotation" | "snapToCursor"> & import("react").RefAttributes<ClearPremoves>>;
```

However, when I rebuild my fork of `react-chessboard` this prop does exist. Could `react-chessboard` be rebuilt and republished?

**Comment by Clariity** [comment]
just published react-chessboard@2.1.1, lmk if the issue is resolved for you

**Comment by leedavidcs** [comment]
Unfortunately, I still don't get the type for `customSquare` when I install `latest`. I re-ran `npm run build` off the latest `main` branch of  this repo and do get `customSquare` on the component type for `Chessboard`, so I'm not certain why this prop is still missing from the installed `latest`.

**Comment by Clariity** [comment]
found the issue, my rollup typescript plugin was caching some type declarations so wasn't outputting the new types, I've added a fix and will republish when I get a chance

**Comment by leedavidcs** [comment]
Thanks! I can confirm `customSquare` is available in types. Closing as completed.
