### ISSUE TITLE
Transform breaks animations

### ISSUE THREAD

**Issue by mono424** [Clariity/react-chessboard#66]
I need to transform: scale() a parent container of the chessboard. Everything works fine, but animations are broken,
is that something you plan to fix, or is that out of scope.

https://user-images.githubusercontent.com/17506411/231532811-70b96926-966d-4a63-a90d-facd1bab627b.mov

**Comment by Clariity** [comment]
when I get a chance I will try to look into this, but it might be difficult to fix due to the implementation of the animations

**Comment by Clariity** [comment]
after a look I don't think it would be a simple or even possible to fix. This may be fixed in the future if I move away from react-dnd but for now using transform: scale() massively breaks drag and drop so I would recommend against it
