### ISSUE TITLE
Pieces can be dragged from a board to another

### ISSUE THREAD

**Issue by Axeltherabbit** [Clariity/react-chessboard#69]
Is this an expected behavior? I didn't see anything in the docs.
Cool feature but it would be better if it's disabled by default?
Also the pieces duplicate 

video: https://imgur.com/a/8fh5gXp

**Comment by Clariity** [comment]
if some chess logic is applied to onPieceDrop then it can return false and prevent the piece being dropped, so functionality is provided to enable users to disable this

**Comment by Axeltherabbit** [comment]
Is there a way to know on which board the piece was dropped?

**Comment by Clariity** [comment]
you can provide a separate onPieceDrop function to each board, the board you drop the piece on will then fire the provided function so you can know based on that

**Comment by Axeltherabbit** [comment]
Thanks

**Comment by Axeltherabbit** [comment]
Reopening because after some testing `onPieceDrop` is not called from a board to another but `getPositionObject` is

**Comment by Clariity** [comment]
```
export const Test = () => {
  function onDrop1(sourceSquare, targetSquare) {
    console.log(1);
    return true;
  }

  function onDrop2(sourceSquare, targetSquare) {
    console.log(2);
    return true;
  }

  return (
    <div style={boardWrapper}>
      <Chessboard id="1" onPieceDrop={onDrop1} />
      <Chessboard id="2" onPieceDrop={onDrop2} />
    </div>
  );
};
```

using the above code it logs the correct values, also the pieces aren't being dropped on the second board so I was unable to replicate the functionality shown in the original video

**Comment by Axeltherabbit** [comment]
Oh, sorry nvm I forgot to add `onPieceDrop` on the other board :sweat_smile:
