### ISSUE TITLE
How to prevent piece captures?

### ISSUE THREAD

**Issue by Epitomaniac** [Clariity/react-chessboard#70]
There is no property for areCapturesAllowed. Is there a way to programmatically disallow captures?

**Comment by Clariity** [comment]
I'm curious as to how you'd want this work? To overlay the pieces? A chess position cannot exist with multiple pieces on the same square

**Comment by Clariity** [comment]
if you just want to prevent a capture you can return false in `onPieceDrop` and the move will be disallowed

**Comment by Epitomaniac** [comment]
I'd like to test whether a user can set up the starting position correctly, I put the pieces randomly on the board and ask the user to set up the pieces; if the user puts a piece on top of another, the piece would be captured which is an unwanted result that breaks the app.

**Comment by Clariity** [comment]
what would you want to happen if a user puts a piece on top of another?

you could instead just return false in onPieceDrop if you don't want the move to happen

ultimately it's up to the react-chessboard user to pass the desired fen position to the board, so the logic can be programmed externally to the package to swap the pieces if desired

**Comment by Epitomaniac** [comment]
> what would you want to happen if a user puts a piece on top of another?

I want the piece to snap back to where is was before the move was made, as if the move was illegal.

> you could instead just return false in onPieceDrop if you don't want the move to happen

How do I check if the move was a capture?

**Comment by Clariity** [comment]
```
export const Example = () => {
  const [game, setGame] = useState(new Chess());

  function onDrop(sourceSquare, targetSquare) {
    if (game.get(targetSquare)) {
      return false;
    }
      
    const gameCopy = { ...game };
    const move = gameCopy.move({
      from: sourceSquare,
      to: targetSquare,
      promotion: "q", // always promote to a queen for example simplicity
    });
    setGame(gameCopy);

    // illegal move
    if (move === null) return false;
    return true;
  }

  return (
    <Chessboard
      id="PlayVsRandom"
      position={game.fen()}
      onPieceDrop={onDrop}
    />
  );
};
```

**Comment by Epitomaniac** [comment]
So this statement makes sure the move has been a capture, right?
`if (game.get(targetSquare) !== null)`
I'll test is once I get back home, thanks for the reply and the wonderful library.
