### ISSUE TITLE
Custom square rendering based on game state

### ISSUE THREAD

**Issue by felipecocco** [Clariity/react-chessboard#71]
Hello,

This is such a wonderful library, and I know what I am trying to do is possible (since you do it on chess openings!) so I thought I'd just ask: How do you achieve the custom rendering of the squares to show possible moves when a piece is clicked? I'd figure there'd be some method to render the board squares based on its position, but I couldn't see it in the docs. Am I missing something obvious?

**Comment by Clariity** [comment]
https://react-chessboard.com/?path=/docs/example-chessboard--click-to-move

Click on the show code button here to see example code

**Comment by felipecocco** [comment]
Omg, so straightforward -- for whatever reason my interpretation of the docs suggested in my head that the customSquareStyle prop would receive an object that would apply those styles to all squares on the board! Thanks, I managed to get it to work perfectly!!!!
