### ISSUE TITLE
Stockfish integration

### ISSUE THREAD

**Issue by kaustavsarkar** [Clariity/react-chessboard#73]
It would be great to have stockfish integrated with the chessboard. I have created some custom in a private repo, but I am more than happy to add the implementation which shall be relevant for a larger audience.

**Comment by Clariity** [comment]
the purpose of this package is to provide a chessboard component, Stockfish can be optionally added separately but I'd like to keep the size of this package small

however it might be good to add it as an example of using the chessboard with stockfish, perhaps you could add a story to the storybook with an example?

**Comment by kaustavsarkar** [comment]
SGTM
