### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by oriyash** [Clariity/react-chessboard#75]
I used this repository extensively in a university project and I would like to ba able to cite the repo in my report. Could you add your citation functionality to the repo please ?

**Comment by Clariity** [comment]
what do you mean by adding my citation functionality?

If you're referencing this repo in a university report and using IEEE standards then my suggestion would be to use a footnote

**Comment by oriyash** [comment]
> what do you mean by adding my citation functionality?
> 
> If you're referencing this repo in a university report and using IEEE standards then my suggestion would be to use a footnote

According to [this article](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) there is a github service to make a repo citable as content

**Comment by Clariity** [comment]
that is for keeping a reference to an archived repository, you can cite this repository using it's URL, it will not change
