### ISSUE TITLE
square style flickering when dragged piece passes over from one square to other

### ISSUE THREAD

**Issue by avi-0** [Clariity/react-chessboard#80]
![Untitled 3](https://github.com/Clariity/react-chessboard/assets/25254726/3d118110-e6ee-4f25-aac1-6b31ec6c1568)

(converting a 60fps vid to gif made a nice slowmo there, actually it's much faster and more annoying, flickering a few times in a row)

In the provided Storybook examples, it occurs in all of them that have draggable pieces except for the first one ("Configurable Board") where it also occurs but rarely and less consistently. Shows up in all combinations of Chrome/Firefox + Win11/Linux Mint for me. I don't understand React well enough to debug this myself so far ngl

**Comment by Clariity** [comment]
I just tested this at https://react-chessboard.vercel.app/?path=/story/example-chessboard--play-vs-random and was unable to reproduce it, it throttled it to a low end device and it still behaved smoothly.

I was using a mouse, were you perhaps using a trackpad?

I will need some more information in order to reproduce the issue

**Comment by avi-0** [comment]
oh, hmm, no, I'm using a mouse on my laptop, specifically HP Pavilion Gaming 17-cd1050ur, i5 10300H, 8GB of RAM, GTX 1650, if that tells you anything, wouldn't be a low end device issue at all. As you can see I thought it was maybe a Linux or Firefox only thing at first, given how noticeable it is for me, and then found it on Windows 11 and Chrome too.

I don't have any other devices to compare at hand, other than my Android phone (no issue on that, all crisp), so idk if it depends on hardware (and why would it?..)

I had an idea it might have to with particular viewport sizes, like if it happens when squares have non-integer dimensions, but I tried adjusting the iframe on that page to make squares's heights exact integers and it doesn't make it go away either.

Can't think of anything else right now, lmk if you have ideas

**Comment by avi-0** [comment]
also I don't get that issue on chessboardjsx, at least not on the example board on https://chessboardjsx.com/, if that's anything

**Comment by Konstantin9658** [comment]
@Clariity Hi, I'm seeing the same problem as described above.

And you can also notice that when a figure is captured, it teleports somewhere to an arbitrary location, I really don’t know how to fix this. Any idea what can be done. Thank you!

https://github.com/Clariity/react-chessboard/assets/76180339/cacbfb79-91c9-4c6a-b959-8419a2568d90

**Comment by banool** [comment]
I'm getting the same issue too, looks the same as the other videos.

**Comment by magicmark** [comment]
same!

**Comment by magicmark** [comment]
FWIW here's a hack to make it work a little better

```jsx
const squareDragRef = useRef<string | null>(null);
```

```jsx
<Chessboard
  onDragOverSquare={(square) => {
    if (squareDragRef.current) {
      const oldSquare = document.querySelector(`div[data-square=${squareDragRef.current}]`)!;
      (oldSquare as HTMLElement).style.boxShadow = '';
    }

    const squareEl = document.querySelector(`div[data-square=${square}]`)!;
    (squareEl as HTMLElement).style.boxShadow = 'inset 0 0 1px 6px rgba(255,255,255,0.75)';
    squareDragRef.current = square;
  }}
  onPieceDragEnd={() =>{
    if (squareDragRef.current) {
      const oldSquare = document.querySelector(`div[data-square=${squareDragRef.current}]`)!;
      (oldSquare as HTMLElement).style.boxShadow = '';
    }
    squareDragRef.current = null;
  }}
/>
```
