### ISSUE TITLE
Use mixins in contrast to inline css

### ISSUE THREAD

**Issue by kaustavsarkar** [Clariity/react-chessboard#89]
### It is more like a feature request than a bug.

I would very much like to get the customisations to cells and chessboard in terms of mixins rather than react component props, which are later used as inline css.

The problem with inline CSS is that if I would like to have a lot of optimisations or styling across my chessboard, I might prefer to have all that styling inside a sass file and overriding inline css is very difficult and sometimes not even possible.

We have faced this issue in certain use cases and we had to manipulate the dom by removing all the inline css and then we added our own css on top of it. This caused a little jank in few cases, but it is acceptable for now.

**Comment by Clariity** [comment]
I've not personally worked with mixins before but this sounds like it would make Sass a dependency of the package, and that is not something I wish to do, please feel free to expand if I am misunderstanding
