### ISSUE TITLE
Using Chessboard causes issue with apps already using react-dnd

### ISSUE THREAD

**Issue by flaw3d** [Clariity/react-chessboard#9]
I have a DndProvider component at the root of my app. When rendering a Chessboard component, this interferes with the rest of the app, disabling drag / drop in the whole app. Is there an option to render a Chessboard without the DndProvider? Or is there some other way this can integrate with apps already using react-dnd?

**Comment by Clariity** [comment]
Are you able to provide some more information to help me understand this issue please?

1. What version of react-dnd are you using?
2. Are you able to place the chessboard outside of your current DndProvider?
3. Is this a known issue with react-dnd by having multiple nested providers?

Relevant information about the dependencies used by react-chessboard:

**Dependencies**
```
 "react-dnd": "^14.0.3",
 "react-dnd-html5-backend": "^14.0.1",
 "react-dnd-multi-backend": "^6.0.2",
 "react-dnd-touch-backend": "^14.1.0"
```

**Usage** (omitted irrelevant code)
```
...
import { DndProvider } from 'react-dnd-multi-backend';
import HTML5toTouch from 'react-dnd-multi-backend/dist/esm/HTML5toTouch';
import { CustomDragLayer } from './components/CustomDragLayer';

export const Chessboard = forwardRef((props, ref) => {
  return (
      <DndProvider options={HTML5toTouch}>
        <ChessboardProvider ref={ref} {...props}>
          <CustomDragLayer />
          <Board />
        </ChessboardProvider>
      </DndProvider>
  );
});
```

**Comment by flaw3d** [comment]
Yeah, here is some more information:

> 1. What version of react-dnd are you using?

"react-dnd": "^14.0.4"
"react-dnd-html5-backend": "^14.0.2"

> 2. Are you able to place the chessboard outside of your current DndProvider?

Just tried that, it seems like this doesn't help, same issue.

> 3. Is this a known issue with react-dnd by having multiple nested providers?

Initially I thought it was, but I tried looking for this issue elsewhere and I didn't find anything so far. However, I did take a deep look within the code and I believe that it is either an issue with react-dnd-html5-backend or the fact that I have two separate copies of react-dnd. This is because the chessboard is a plugin loaded dynamically so the plugin has it's own dependencies bundled (react-dom and react-chessboard).

I was able to find the code below: https://github.com/react-dnd/react-dnd/blob/main/packages/backend-html5/src/HTML5BackendImpl.ts#L514
```ts
public handleTopDragStart = (e: DragEvent): void => {
...
  } else {
    // If by this time no drag source reacted, tell browser not to drag.
    e.preventDefault()
  }
}
```
So I have draggable tabs and this draggable chessboard.
When commenting out the `e.preventDefault()` in both instances of the html5 backend, drag and drop for chessboard begins to work again. And I am able to drag the tabs again, but they aren't dropping properly (not moving positions on release).

I think it's this unique scenario of having two copies of react & react-dnd that's causing the issue. I just wish the react-dnd  html5 backend used in the core app wouldn't pick up and throw away the event when I am dragging pieces of the chessboard (and vice-versa).

> 4. Interfering how?

Drag and drop just stops working. I have draggable tabs and this chessboard but none of if works when both are in the app.

**Comment by flaw3d** [comment]
I was able to solve the issue by providing the `rootElement` option to both html5 backends (the one my app is using, and the one used in react-chessboard)

I found this over here: https://github.com/react-dnd/react-dnd/issues/3344

I also had to wrap the DndProvider around the tab bar instead of the root app. Now dragging works again but one caveat is that I cannot move/hover chess pieces outside of the chessboard. The pieces just get locked at the edge of the chessboard when moving my mouse out. I don't know why this happens because my tabs can still be dragged anywhere across the app.

Anyway, for now this works for me. Below is an example of the modified react-chessboard that I am using to work with this. Code is based on the sandbox code from the link above.

```js
import { forwardRef, useState, useCallback, useMemo } from 'react';
import { DndProvider, TouchTransition, MouseTransition } from 'react-dnd-multi-backend';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { TouchBackend } from 'react-dnd-touch-backend';

import { Board } from './components/Board';
import { CustomDragLayer } from './components/CustomDragLayer';
import { ErrorBoundary } from './components/ErrorBoundary';
// import SparePieces from './components/SparePieces';

import { chessboardDefaultProps, chessboardPropTypes } from './consts';
import { ChessboardProvider } from './context/chessboard-context';

const useDndProvider = () => {
  const [dndArea, setDndArea] = useState();
  const handleRef = useCallback((node) => setDndArea(node), []);
  const customHtml5ToTouch = useMemo(
    () => {
      return {
        backends: [
          {
            id: 'html5',
            backend: HTML5Backend,
            options: { rootElement: dndArea },
            transition: MouseTransition
          },
          {
            id: 'touch',
            backend: TouchBackend,
            options: { enableMouseEvents: true },
            preview: true,
            transition: TouchTransition
          }
        ]
      };
    },
    [dndArea]
  );
  return { dndArea, handleRef, customHtml5ToTouch };
};

export const Chessboard = forwardRef((props, ref) => {
  const { dndArea, handleRef, customHtml5ToTouch } = useDndProvider();

  return (
    <ErrorBoundary>
      <div ref={handleRef}>
        {dndArea && (
          <DndProvider options={customHtml5ToTouch}>
            <ChessboardProvider ref={ref} {...props}>
              <CustomDragLayer />
              <div>
                {/* {props.showSparePieces && <SparePieces.Top />} */}
                <Board />
                {/* {props.showSparePieces && <SparePieces.Bottom />} */}
              </div>
            </ChessboardProvider>
          </DndProvider>
        )}
      </div>
    </ErrorBoundary>
  );
});

Chessboard.propTypes = chessboardPropTypes;
Chessboard.defaultProps = chessboardDefaultProps;

```

**Comment by Clariity** [comment]
I'm glad you've found a solution that works for you, and it looks like the issue is due to nested DnDProviders from react-dnd/react-dnd-multi-backend

I've had constant issues with react-dnd and the packages aren't updated that often and have hundreds of open issues. I just about got it in a working state with this package itself for mobile and web, and even looking at the code feels like it will break it. Do you think any changes need to be made to react-chessboard?

**Comment by flaw3d** [comment]
I don't think the above change should be made for that reason. Although it seems to be working fine for me, I did notice that one difference is pieces being locked inside the board when dragging, and there might be other unknown issues with this change as well.

I think changes just need to be made with the react-dnd-html5-backend. The html5 backend shouldn't throw away events that it doesn't use for dragging, but it looks like it does.

Feel free to close the issue. If I ever find some fix for the "pieces being locked inside the board" bug that comes with the above change or find some better alternative to react-dnd, I'd be happy to make a pull request.
