### ISSUE TITLE
Allow for customization of every unique piece not just the different colored pieces. 

### ISSUE THREAD

**Issue by camfung** [Clariity/react-chessboard#91]
Currently you are only able to control the different colored pieces. ie all the white pawns will look the same and all the black knights will look the same. 
I would like to be able to have full controll of each and every piece.

**Comment by camfung** [comment]
I've worked through the problem and I now realize that if I add square to the CustomPieceFnArgs. I can uniquely identify by the square that the piece is on. 
`export type CustomPieceFnArgs = {
  isDragging: boolean;
  squareWidth: number;
  square: Square;
};`
`(chessPieces[piece] as CustomPieceFn)({
          squareWidth: boardWidth / 8,
          isDragging,
          square,
        })`

**Comment by Clariity** [comment]
I think if more arguments were passed here that are already defined (such as sourceSquare), then this could be achieved:

https://github.com/Clariity/react-chessboard/blob/main/src/chessboard/components/Piece.tsx#L178-L179

If you want to raise a PR for this functionality then please do

**Comment by Clariity** [comment]
fixed in #102 

Will release a new version soon
